ui_generated_text = '''# This file is auto-generated by addon AutoRefSpace
# http://julienduroure.com/AutoRefSpace
# for any questions, please ask contact@julienduroure.com
##########################################################################################
#	GPL LICENSE:
#-------------------------
# This file is part of AutoRefSpace.
#
#    AutoRefSpace is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    AutoRefSpace is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with AutoRefSpace.  If not, see <http://www.gnu.org/licenses/>.
##########################################################################################
#
#	Copyright 2016 Julien Duroure (contact@julienduroure.com)
#
##########################################################################################
import bpy

autorefspace_rig_id = "###rig_id###"

###ITEM_LISTS###

def cb_enum_items(self, context):
###ITEM_CHOICE###

bpy.types.PoseBone.autorefspace_enum = bpy.props.EnumProperty(name = 'enum', items=cb_enum_items)

class POSE_PT_JuAR_AutoRefSpace_###rig_id###(bpy.types.Panel):
	bl_label = "###LABEL###"
	bl_space_type = 'VIEW_3D'
	bl_region_type = '###REGION_TYPE###'
	bl_category = "###CATEGORY###"
	
	@classmethod
	def poll(self, context):
		return context.active_object and context.active_object.type == "ARMATURE" and context.active_object.data.get("autorefspace_rig_id") is not None and context.active_object.data.get("autorefspace_rig_id") == autorefspace_rig_id and context.mode == 'POSE'
		
			
	def draw(self, context):
		layout = self.layout
		armature = context.object
		
		refspace_tab = ###REFSPACE_TAB###
		
		row = layout.row()
		if context.active_pose_bone and context.active_pose_bone.name in refspace_tab:
			row.prop(context.active_pose_bone, "autorefspace_enum", text="RefSpace")

def register():
	bpy.utils.register_class(POSE_PT_JuAR_AutoRefSpace_###rig_id###)
	
def unregister():
	bpy.utils.unregister_class(POSE_PT_JuAR_AutoRefSpace_###rig_id###)

register()
'''


driver_generated_text = '''# This file is auto-generated by addon AutoRefSpace
# http://julienduroure.com/AutoRefSpace
# for any questions, please ask contact@julienduroure.com
##########################################################################################
#	GPL LICENSE:
#-------------------------
# This file is part of AutoRefSpace.
#
#    AutoRefSpace is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    AutoRefSpace is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with AutoRefSpace.  If not, see <http://www.gnu.org/licenses/>.
##########################################################################################
#
#	Copyright 2016 Julien Duroure (contact@julienduroure.com)
#
##########################################################################################
import bpy

###DRIVERS###

'''